
import { auth } from "@/auth";
import { refreshPage } from "../actions";
import Navbar from "../components/navbar/Navbar";
import "../globals.css";
import { dbConnect } from "../services";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({ children }) {
  await dbConnect();
  await refreshPage();
  await auth();
  return (
    <html lang="en">
      <body
      >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
